/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tareaTcpRmiUdpBdPropio;

/**
 *
 * @author eantoniocf
 */

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.HashMap;
import java.util.Map;
import javax.swing.table.DefaultTableModel;


public class ClienteTCPGrafico extends javax.swing.JFrame {

    /**
     * Creates new form ClienteTCPGrafico
     */
    
    private Socket client;
    private DataInputStream fromServer;
    private DataOutputStream toServer;
    private Map<String, Map<String, String>> deudas;
    
    public ClienteTCPGrafico() {
        initComponents();
        deudas = new HashMap<>();
        connectToServer();
    }
    private void connectToServer() {
        int port = 5002;
        try {
            client = new Socket("192.168.185.159", port);
            fromServer = new DataInputStream(client.getInputStream());
            toServer = new DataOutputStream(client.getOutputStream());
        } catch (IOException e) {
            jTextoSalida.setText("Error al conectar con el servidor.");
        }
    }
    private void updateTable() {
        DefaultTableModel model = (DefaultTableModel) jTablaDeudas.getModel();
        model.setRowCount(0); // Clear existing rows
        
        for (Map.Entry<String, Map<String, String>> entry : deudas.entrySet()) {
            String deudaId = entry.getKey();
            Map<String, String> detalles = entry.getValue();
            model.addRow(new Object[]{
                deudaId,
                detalles.get("ci"),
                detalles.get("anio"),
                detalles.get("impuesto"),
                detalles.get("monto")
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextFieldCi = new javax.swing.JTextField();
        jBotonBuscarCi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaDeudas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jBotonPagar = new javax.swing.JButton();
        jTextoSalida = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel2.setText("BUSCAR DEUDAS");

        jTextFieldCi.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jTextFieldCi.setToolTipText("Ingrese su C.I.");
        jTextFieldCi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCiActionPerformed(evt);
            }
        });

        jBotonBuscarCi.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jBotonBuscarCi.setText("Buscar");
        jBotonBuscarCi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonBuscarCiActionPerformed(evt);
            }
        });

        jTablaDeudas.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jTablaDeudas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Index", "C.I.", "Anio", "Impuesto", "Monto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablaDeudas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTablaDeudas);
        if (jTablaDeudas.getColumnModel().getColumnCount() > 0) {
            jTablaDeudas.getColumnModel().getColumn(0).setResizable(false);
            jTablaDeudas.getColumnModel().getColumn(1).setResizable(false);
            jTablaDeudas.getColumnModel().getColumn(2).setResizable(false);
            jTablaDeudas.getColumnModel().getColumn(3).setResizable(false);
            jTablaDeudas.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setText("SELECCIONE LA DEUDA QUE DESEA PAGAR");

        jBotonPagar.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jBotonPagar.setText("PAGAR DEUDA");
        jBotonPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonPagarActionPerformed(evt);
            }
        });

        jTextoSalida.setEditable(false);
        jTextoSalida.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jTextoSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextoSalidaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setText("OUTPUT");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 2, 14)); // NOI18N
        jLabel4.setText("Ingrese su C.I.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextoSalida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(68, 68, 68))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldCi)
                                .addComponent(jBotonBuscarCi, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jBotonPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldCi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBotonBuscarCi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBotonPagar)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCiActionPerformed
        
    }//GEN-LAST:event_jTextFieldCiActionPerformed

    private void jBotonBuscarCiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonBuscarCiActionPerformed
        String ci = jTextFieldCi.getText().trim();
        if (ci.isEmpty()) {
            jTextoSalida.setText("Ingrese un C.I.");
            return;
        }

        try {
            deudas.clear();
            String mensajeCliente = "buscar_ " + ci;
            toServer.writeUTF(mensajeCliente);
            String mensajeServidor = fromServer.readUTF();

            if (mensajeServidor.contains("-")) {
                String[] partes = mensajeServidor.split("\\.");
                for (String deudaString : partes) {
                    String[] subPartes = deudaString.split("-");
                    String deudaId = subPartes[0];
                    String[] llavesYDatos = subPartes[1].split(",");
                    Map<String, String> detallesDeuda = new HashMap<>();
                    for (String llaveDato : llavesYDatos) {
                        String[] llaveDatoSeparado = llaveDato.split(":");
                        detallesDeuda.put(llaveDatoSeparado[0].trim(), llaveDatoSeparado[1].trim());
                    }
                    deudas.put(deudaId, detallesDeuda);
                }
                updateTable();
                jTextoSalida.setText("Deudas encontradas.");
            } else {
                jTextoSalida.setText("No hay deudas para el C.I. proporcionado.");
                updateTable();
            }
        } catch (IOException e) {
            jTextoSalida.setText("Error al buscar deudas.");
        }
    }//GEN-LAST:event_jBotonBuscarCiActionPerformed

    private void jBotonPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonPagarActionPerformed
        int selectedRow = jTablaDeudas.getSelectedRow();
        if (selectedRow == -1) {
            jTextoSalida.setText("Seleccione una deuda para pagar.");
            return;
        }

        String deudaId = (String) jTablaDeudas.getValueAt(selectedRow, 0);
        Map<String, String> selectedDeuda = deudas.get(deudaId);
        if (selectedDeuda != null) {
            String result = String.format("ci:%s,anio:%s,impuesto:%s,monto:%s",
                    selectedDeuda.get("ci"),
                    selectedDeuda.get("anio"),
                    selectedDeuda.get("impuesto"),
                    selectedDeuda.get("monto"));

            try {
                String mensajeCliente = "pagar_" + result;
                toServer.writeUTF(mensajeCliente);
                String mensajeServidor = fromServer.readUTF();

                if (mensajeServidor.contains("Deuda pagada exitosamente")) {
                    deudas.remove(deudaId);
                    updateTable();
                    jTextoSalida.setText("Deuda pagada con éxito.");
                } else {
                    jTextoSalida.setText("Error al pagar la deuda. Su C.I. tiene observaciones");
                }
            } catch (IOException e) {
                jTextoSalida.setText("Error al pagar deuda.");
            }
        } else {
            jTextoSalida.setText("Deuda no encontrada.");
        }
    }//GEN-LAST:event_jBotonPagarActionPerformed

    private void jTextoSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextoSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextoSalidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteTCPGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteTCPGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteTCPGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteTCPGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteTCPGrafico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotonBuscarCi;
    private javax.swing.JButton jBotonPagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaDeudas;
    private javax.swing.JTextField jTextFieldCi;
    private javax.swing.JTextField jTextoSalida;
    // End of variables declaration//GEN-END:variables
}
